name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on pushes to tags starting with 'v' with semantic versioning, e.g., v1.0.0

jobs:
  package_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create the release and upload assets
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # To get full commit history for release notes

      - name: Package distribution
        run: |
          zip -r dist.zip dist

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist.zip
          generate_release_notes: true # Generate automatic release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
